services:
  firefly-buddy:
    container_name: firefly-buddy
    image: ghcr.io/skb50bd/firefly-iii-ai-ingest:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=buddy-db;Database=firefly_buddy;Username=postgres;Password=password
    env_file:
      - .env
    depends_on:
      buddy-db:
        condition: service_healthy
    networks:
      - firefly-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  buddy-db:
    container_name: buddy-db
    image: postgres:17
    volumes:
    - ./buddy/db:/var/lib/postgresql/data
    env_file: .db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    cpus: 8
    mem_limit: 8gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - firefly-network

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - /dev/dri:/dev/dri
    networks:
      - firefly-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:

networks:
  firefly-network:
    driver: bridge
