// <auto-generated>
/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Brotal.FireflyIII.Client;

namespace Brotal.FireflyIII.Model
{
    /// <summary>
    /// The object class to which the attachment must be linked.
    /// </summary>
    /// <value>The object class to which the attachment must be linked.</value>
    public enum AttachableType
    {
        /// <summary>
        /// Enum Account for value: Account
        /// </summary>
        Account = 1,

        /// <summary>
        /// Enum Budget for value: Budget
        /// </summary>
        Budget = 2,

        /// <summary>
        /// Enum Bill for value: Bill
        /// </summary>
        Bill = 3,

        /// <summary>
        /// Enum TransactionJournal for value: TransactionJournal
        /// </summary>
        TransactionJournal = 4,

        /// <summary>
        /// Enum PiggyBank for value: PiggyBank
        /// </summary>
        PiggyBank = 5,

        /// <summary>
        /// Enum Tag for value: Tag
        /// </summary>
        Tag = 6
    }

    /// <summary>
    /// Converts <see cref="AttachableType"/> to and from the JSON value
    /// </summary>
    public static class AttachableTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="AttachableType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AttachableType FromString(string value)
        {
            if (value.Equals("Account"))
                return AttachableType.Account;

            if (value.Equals("Budget"))
                return AttachableType.Budget;

            if (value.Equals("Bill"))
                return AttachableType.Bill;

            if (value.Equals("TransactionJournal"))
                return AttachableType.TransactionJournal;

            if (value.Equals("PiggyBank"))
                return AttachableType.PiggyBank;

            if (value.Equals("Tag"))
                return AttachableType.Tag;

            throw new NotImplementedException($"Could not convert value to type AttachableType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="AttachableType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AttachableType? FromStringOrDefault(string value)
        {
            if (value.Equals("Account"))
                return AttachableType.Account;

            if (value.Equals("Budget"))
                return AttachableType.Budget;

            if (value.Equals("Bill"))
                return AttachableType.Bill;

            if (value.Equals("TransactionJournal"))
                return AttachableType.TransactionJournal;

            if (value.Equals("PiggyBank"))
                return AttachableType.PiggyBank;

            if (value.Equals("Tag"))
                return AttachableType.Tag;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AttachableType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(AttachableType value)
        {
            if (value == AttachableType.Account)
                return "Account";

            if (value == AttachableType.Budget)
                return "Budget";

            if (value == AttachableType.Bill)
                return "Bill";

            if (value == AttachableType.TransactionJournal)
                return "TransactionJournal";

            if (value == AttachableType.PiggyBank)
                return "PiggyBank";

            if (value == AttachableType.Tag)
                return "Tag";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AttachableType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class AttachableTypeJsonConverter : JsonConverter<AttachableType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AttachableType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            AttachableType? result = rawValue == null
                ? null
                : AttachableTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the AttachableType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="attachableType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AttachableType attachableType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(AttachableTypeValueConverter.ToJsonValue(attachableType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AttachableType"/>
    /// </summary>
    public class AttachableTypeNullableJsonConverter : JsonConverter<AttachableType?>
    {
        /// <summary>
        /// Returns a AttachableType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AttachableType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            AttachableType? result = rawValue == null
                ? null
                : AttachableTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the AttachableType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="attachableType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AttachableType? attachableType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(attachableType.HasValue ? AttachableTypeValueConverter.ToJsonValue(attachableType.Value).ToString() : "null");
        }
    }
}
