// <auto-generated>
/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Brotal.FireflyIII.Client;

namespace Brotal.FireflyIII.Model
{
    /// <summary>
    /// Mandatory when the account_role is ccAsset. Can only be monthlyFull or null.
    /// </summary>
    /// <value>Mandatory when the account_role is ccAsset. Can only be monthlyFull or null.</value>
    public enum CreditCardTypeProperty
    {
        /// <summary>
        /// Enum MonthlyFull for value: monthlyFull
        /// </summary>
        MonthlyFull = 1
    }

    /// <summary>
    /// Converts <see cref="CreditCardTypeProperty"/> to and from the JSON value
    /// </summary>
    public static class CreditCardTypePropertyValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CreditCardTypeProperty"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CreditCardTypeProperty FromString(string value)
        {
            if (value.Equals("monthlyFull"))
                return CreditCardTypeProperty.MonthlyFull;

            throw new NotImplementedException($"Could not convert value to type CreditCardTypeProperty: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CreditCardTypeProperty"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CreditCardTypeProperty? FromStringOrDefault(string value)
        {
            if (value.Equals("monthlyFull"))
                return CreditCardTypeProperty.MonthlyFull;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CreditCardTypeProperty"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(CreditCardTypeProperty value)
        {
            if (value == CreditCardTypeProperty.MonthlyFull)
                return "monthlyFull";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreditCardTypeProperty"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CreditCardTypePropertyJsonConverter : JsonConverter<CreditCardTypeProperty>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CreditCardTypeProperty Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CreditCardTypeProperty? result = rawValue == null
                ? null
                : CreditCardTypePropertyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CreditCardTypeProperty to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="creditCardTypeProperty"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CreditCardTypeProperty creditCardTypeProperty, JsonSerializerOptions options)
        {
            writer.WriteStringValue(CreditCardTypePropertyValueConverter.ToJsonValue(creditCardTypeProperty).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreditCardTypeProperty"/>
    /// </summary>
    public class CreditCardTypePropertyNullableJsonConverter : JsonConverter<CreditCardTypeProperty?>
    {
        /// <summary>
        /// Returns a CreditCardTypeProperty from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CreditCardTypeProperty? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CreditCardTypeProperty? result = rawValue == null
                ? null
                : CreditCardTypePropertyValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CreditCardTypeProperty to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="creditCardTypeProperty"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CreditCardTypeProperty? creditCardTypeProperty, JsonSerializerOptions options)
        {
            writer.WriteStringValue(creditCardTypeProperty.HasValue ? CreditCardTypePropertyValueConverter.ToJsonValue(creditCardTypeProperty.Value).ToString() : "null");
        }
    }
}
