// <auto-generated>
/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Brotal.FireflyIII.Client;

namespace Brotal.FireflyIII.Model
{
    /// <summary>
    /// CronResult
    /// </summary>
    public partial class CronResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CronResult" /> class.
        /// </summary>
        /// <param name="recurringTransactions">recurringTransactions</param>
        /// <param name="autoBudgets">autoBudgets</param>
        /// <param name="telemetry">telemetry</param>
        [JsonConstructor]
        public CronResult(Option<CronResultRow?> recurringTransactions = default, Option<CronResultRow?> autoBudgets = default, Option<CronResultRow?> telemetry = default)
        {
            RecurringTransactionsOption = recurringTransactions;
            AutoBudgetsOption = autoBudgets;
            TelemetryOption = telemetry;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of RecurringTransactions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CronResultRow?> RecurringTransactionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets RecurringTransactions
        /// </summary>
        [JsonPropertyName("recurring_transactions")]
        public CronResultRow? RecurringTransactions { get { return this.RecurringTransactionsOption; } set { this.RecurringTransactionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AutoBudgets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CronResultRow?> AutoBudgetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AutoBudgets
        /// </summary>
        [JsonPropertyName("auto_budgets")]
        public CronResultRow? AutoBudgets { get { return this.AutoBudgetsOption; } set { this.AutoBudgetsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Telemetry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CronResultRow?> TelemetryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Telemetry
        /// </summary>
        [JsonPropertyName("telemetry")]
        public CronResultRow? Telemetry { get { return this.TelemetryOption; } set { this.TelemetryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CronResult {\n");
            sb.Append("  RecurringTransactions: ").Append(RecurringTransactions).Append("\n");
            sb.Append("  AutoBudgets: ").Append(AutoBudgets).Append("\n");
            sb.Append("  Telemetry: ").Append(Telemetry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CronResult" />
    /// </summary>
    public class CronResultJsonConverter : JsonConverter<CronResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="CronResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CronResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CronResultRow?> recurringTransactions = default;
            Option<CronResultRow?> autoBudgets = default;
            Option<CronResultRow?> telemetry = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recurring_transactions":
                            recurringTransactions = new Option<CronResultRow?>(JsonSerializer.Deserialize<CronResultRow>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "auto_budgets":
                            autoBudgets = new Option<CronResultRow?>(JsonSerializer.Deserialize<CronResultRow>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "telemetry":
                            telemetry = new Option<CronResultRow?>(JsonSerializer.Deserialize<CronResultRow>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (recurringTransactions.IsSet && recurringTransactions.Value == null)
                throw new ArgumentNullException(nameof(recurringTransactions), "Property is not nullable for class CronResult.");

            if (autoBudgets.IsSet && autoBudgets.Value == null)
                throw new ArgumentNullException(nameof(autoBudgets), "Property is not nullable for class CronResult.");

            if (telemetry.IsSet && telemetry.Value == null)
                throw new ArgumentNullException(nameof(telemetry), "Property is not nullable for class CronResult.");

            return new CronResult(recurringTransactions, autoBudgets, telemetry);
        }

        /// <summary>
        /// Serializes a <see cref="CronResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cronResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CronResult cronResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, cronResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CronResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cronResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CronResult cronResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (cronResult.RecurringTransactionsOption.IsSet && cronResult.RecurringTransactions == null)
                throw new ArgumentNullException(nameof(cronResult.RecurringTransactions), "Property is required for class CronResult.");

            if (cronResult.AutoBudgetsOption.IsSet && cronResult.AutoBudgets == null)
                throw new ArgumentNullException(nameof(cronResult.AutoBudgets), "Property is required for class CronResult.");

            if (cronResult.TelemetryOption.IsSet && cronResult.Telemetry == null)
                throw new ArgumentNullException(nameof(cronResult.Telemetry), "Property is required for class CronResult.");

            if (cronResult.RecurringTransactionsOption.IsSet)
            {
                writer.WritePropertyName("recurring_transactions");
                JsonSerializer.Serialize(writer, cronResult.RecurringTransactions, jsonSerializerOptions);
            }
            if (cronResult.AutoBudgetsOption.IsSet)
            {
                writer.WritePropertyName("auto_budgets");
                JsonSerializer.Serialize(writer, cronResult.AutoBudgets, jsonSerializerOptions);
            }
            if (cronResult.TelemetryOption.IsSet)
            {
                writer.WritePropertyName("telemetry");
                JsonSerializer.Serialize(writer, cronResult.Telemetry, jsonSerializerOptions);
            }
        }
    }
}
