// <auto-generated>
/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Brotal.FireflyIII.Client;

namespace Brotal.FireflyIII.Model
{
    /// <summary>
    /// TransactionLink
    /// </summary>
    public partial class TransactionLink : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionLink" /> class.
        /// </summary>
        /// <param name="linkTypeId">The link type ID to use. You can also use the link_type_name field.</param>
        /// <param name="inwardId">The inward transaction transaction_journal_id for the link. This becomes the &#39;is paid by&#39; transaction of the set.</param>
        /// <param name="outwardId">The outward transaction transaction_journal_id for the link. This becomes the &#39;pays for&#39; transaction of the set.</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="linkTypeName">The link type name to use. You can also use the link_type_id field.</param>
        /// <param name="notes">Optional. Some notes.</param>
        [JsonConstructor]
        public TransactionLink(string linkTypeId, string inwardId, string outwardId, Option<DateTime?> createdAt = default, Option<DateTime?> updatedAt = default, Option<string?> linkTypeName = default, Option<string?> notes = default)
        {
            LinkTypeId = linkTypeId;
            InwardId = inwardId;
            OutwardId = outwardId;
            CreatedAtOption = createdAt;
            UpdatedAtOption = updatedAt;
            LinkTypeNameOption = linkTypeName;
            NotesOption = notes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The link type ID to use. You can also use the link_type_name field.
        /// </summary>
        /// <value>The link type ID to use. You can also use the link_type_name field.</value>
        /* <example>5</example> */
        [JsonPropertyName("link_type_id")]
        public string LinkTypeId { get; set; }

        /// <summary>
        /// The inward transaction transaction_journal_id for the link. This becomes the &#39;is paid by&#39; transaction of the set.
        /// </summary>
        /// <value>The inward transaction transaction_journal_id for the link. This becomes the &#39;is paid by&#39; transaction of the set.</value>
        /* <example>131</example> */
        [JsonPropertyName("inward_id")]
        public string InwardId { get; set; }

        /// <summary>
        /// The outward transaction transaction_journal_id for the link. This becomes the &#39;pays for&#39; transaction of the set.
        /// </summary>
        /// <value>The outward transaction transaction_journal_id for the link. This becomes the &#39;pays for&#39; transaction of the set.</value>
        /* <example>131</example> */
        [JsonPropertyName("outward_id")]
        public string OutwardId { get; set; }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /* <example>2025-08-01T00:00Z</example> */
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption; } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedAtOption { get; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /* <example>2025-08-01T00:00Z</example> */
        [JsonPropertyName("updated_at")]
        public DateTime? UpdatedAt { get { return this.UpdatedAtOption; } }

        /// <summary>
        /// Used to track the state of LinkTypeName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkTypeNameOption { get; private set; }

        /// <summary>
        /// The link type name to use. You can also use the link_type_id field.
        /// </summary>
        /// <value>The link type name to use. You can also use the link_type_id field.</value>
        /* <example>Is paid by</example> */
        [JsonPropertyName("link_type_name")]
        public string? LinkTypeName { get { return this.LinkTypeNameOption; } set { this.LinkTypeNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Optional. Some notes.
        /// </summary>
        /// <value>Optional. Some notes.</value>
        /* <example>Some example notes</example> */
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionLink {\n");
            sb.Append("  LinkTypeId: ").Append(LinkTypeId).Append("\n");
            sb.Append("  InwardId: ").Append(InwardId).Append("\n");
            sb.Append("  OutwardId: ").Append(OutwardId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  LinkTypeName: ").Append(LinkTypeName).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TransactionLink" />
    /// </summary>
    public class TransactionLinkJsonConverter : JsonConverter<TransactionLink>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TransactionLink" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TransactionLink Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> linkTypeId = default;
            Option<string?> inwardId = default;
            Option<string?> outwardId = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> linkTypeName = default;
            Option<string?> notes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "link_type_id":
                            linkTypeId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "inward_id":
                            inwardId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "outward_id":
                            outwardId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "link_type_name":
                            linkTypeName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!linkTypeId.IsSet)
                throw new ArgumentException("Property is required for class TransactionLink.", nameof(linkTypeId));

            if (!inwardId.IsSet)
                throw new ArgumentException("Property is required for class TransactionLink.", nameof(inwardId));

            if (!outwardId.IsSet)
                throw new ArgumentException("Property is required for class TransactionLink.", nameof(outwardId));

            if (linkTypeId.IsSet && linkTypeId.Value == null)
                throw new ArgumentNullException(nameof(linkTypeId), "Property is not nullable for class TransactionLink.");

            if (inwardId.IsSet && inwardId.Value == null)
                throw new ArgumentNullException(nameof(inwardId), "Property is not nullable for class TransactionLink.");

            if (outwardId.IsSet && outwardId.Value == null)
                throw new ArgumentNullException(nameof(outwardId), "Property is not nullable for class TransactionLink.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class TransactionLink.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class TransactionLink.");

            if (linkTypeName.IsSet && linkTypeName.Value == null)
                throw new ArgumentNullException(nameof(linkTypeName), "Property is not nullable for class TransactionLink.");

            return new TransactionLink(linkTypeId.Value!, inwardId.Value!, outwardId.Value!, createdAt, updatedAt, linkTypeName, notes);
        }

        /// <summary>
        /// Serializes a <see cref="TransactionLink" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transactionLink"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TransactionLink transactionLink, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, transactionLink, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TransactionLink" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transactionLink"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TransactionLink transactionLink, JsonSerializerOptions jsonSerializerOptions)
        {
            if (transactionLink.LinkTypeId == null)
                throw new ArgumentNullException(nameof(transactionLink.LinkTypeId), "Property is required for class TransactionLink.");

            if (transactionLink.InwardId == null)
                throw new ArgumentNullException(nameof(transactionLink.InwardId), "Property is required for class TransactionLink.");

            if (transactionLink.OutwardId == null)
                throw new ArgumentNullException(nameof(transactionLink.OutwardId), "Property is required for class TransactionLink.");

            if (transactionLink.LinkTypeNameOption.IsSet && transactionLink.LinkTypeName == null)
                throw new ArgumentNullException(nameof(transactionLink.LinkTypeName), "Property is required for class TransactionLink.");

            writer.WriteString("link_type_id", transactionLink.LinkTypeId);

            writer.WriteString("inward_id", transactionLink.InwardId);

            writer.WriteString("outward_id", transactionLink.OutwardId);

            if (transactionLink.CreatedAtOption.IsSet)
                writer.WriteString("created_at", transactionLink.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (transactionLink.UpdatedAtOption.IsSet)
                writer.WriteString("updated_at", transactionLink.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));

            if (transactionLink.LinkTypeNameOption.IsSet)
                writer.WriteString("link_type_name", transactionLink.LinkTypeName);

            if (transactionLink.NotesOption.IsSet)
                if (transactionLink.NotesOption.Value != null)
                    writer.WriteString("notes", transactionLink.Notes);
                else
                    writer.WriteNull("notes");
        }
    }
}
