// <auto-generated>
/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Brotal.FireflyIII.Client;

namespace Brotal.FireflyIII.Model
{
    /// <summary>
    /// Indicator for what Firefly III will deliver to the webhook URL.
    /// </summary>
    /// <value>Indicator for what Firefly III will deliver to the webhook URL.</value>
    public enum WebhookResponse
    {
        /// <summary>
        /// Enum TRANSACTIONS for value: TRANSACTIONS
        /// </summary>
        TRANSACTIONS = 1,

        /// <summary>
        /// Enum ACCOUNTS for value: ACCOUNTS
        /// </summary>
        ACCOUNTS = 2,

        /// <summary>
        /// Enum NONE for value: NONE
        /// </summary>
        NONE = 3
    }

    /// <summary>
    /// Converts <see cref="WebhookResponse"/> to and from the JSON value
    /// </summary>
    public static class WebhookResponseValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="WebhookResponse"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WebhookResponse FromString(string value)
        {
            if (value.Equals("TRANSACTIONS"))
                return WebhookResponse.TRANSACTIONS;

            if (value.Equals("ACCOUNTS"))
                return WebhookResponse.ACCOUNTS;

            if (value.Equals("NONE"))
                return WebhookResponse.NONE;

            throw new NotImplementedException($"Could not convert value to type WebhookResponse: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="WebhookResponse"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WebhookResponse? FromStringOrDefault(string value)
        {
            if (value.Equals("TRANSACTIONS"))
                return WebhookResponse.TRANSACTIONS;

            if (value.Equals("ACCOUNTS"))
                return WebhookResponse.ACCOUNTS;

            if (value.Equals("NONE"))
                return WebhookResponse.NONE;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="WebhookResponse"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(WebhookResponse value)
        {
            if (value == WebhookResponse.TRANSACTIONS)
                return "TRANSACTIONS";

            if (value == WebhookResponse.ACCOUNTS)
                return "ACCOUNTS";

            if (value == WebhookResponse.NONE)
                return "NONE";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookResponse"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class WebhookResponseJsonConverter : JsonConverter<WebhookResponse>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WebhookResponse Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            WebhookResponse? result = rawValue == null
                ? null
                : WebhookResponseValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the WebhookResponse to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResponse"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WebhookResponse webhookResponse, JsonSerializerOptions options)
        {
            writer.WriteStringValue(WebhookResponseValueConverter.ToJsonValue(webhookResponse).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookResponse"/>
    /// </summary>
    public class WebhookResponseNullableJsonConverter : JsonConverter<WebhookResponse?>
    {
        /// <summary>
        /// Returns a WebhookResponse from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WebhookResponse? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            WebhookResponse? result = rawValue == null
                ? null
                : WebhookResponseValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the WebhookResponse to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResponse"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WebhookResponse? webhookResponse, JsonSerializerOptions options)
        {
            writer.WriteStringValue(webhookResponse.HasValue ? WebhookResponseValueConverter.ToJsonValue(webhookResponse.Value).ToString() : "null");
        }
    }
}
