/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Brotal.FireflyIII.Model;
using Brotal.FireflyIII.Client;
using System.Reflection;

namespace Brotal.FireflyIII.Test.Model
{
    /// <summary>
    ///  Class for testing AutocompleteAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutocompleteAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutocompleteAccount
        //private AutocompleteAccount instance;

        public AutocompleteAccountTests()
        {
            // TODO uncomment below to create an instance of AutocompleteAccount
            //instance = new AutocompleteAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutocompleteAccount
        /// </summary>
        [Fact]
        public void AutocompleteAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutocompleteAccount
            //Assert.IsType<AutocompleteAccount>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'NameWithBalance'
        /// </summary>
        [Fact]
        public void NameWithBalanceTest()
        {
            // TODO unit test for the property 'NameWithBalance'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }

        /// <summary>
        /// Test the property 'CurrencyName'
        /// </summary>
        [Fact]
        public void CurrencyNameTest()
        {
            // TODO unit test for the property 'CurrencyName'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Fact]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }

        /// <summary>
        /// Test the property 'CurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void CurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'CurrencyDecimalPlaces'
        }

        /// <summary>
        /// Test the property 'AccountCurrencyId'
        /// </summary>
        [Fact]
        public void AccountCurrencyIdTest()
        {
            // TODO unit test for the property 'AccountCurrencyId'
        }

        /// <summary>
        /// Test the property 'AccountCurrencyName'
        /// </summary>
        [Fact]
        public void AccountCurrencyNameTest()
        {
            // TODO unit test for the property 'AccountCurrencyName'
        }

        /// <summary>
        /// Test the property 'AccountCurrencyCode'
        /// </summary>
        [Fact]
        public void AccountCurrencyCodeTest()
        {
            // TODO unit test for the property 'AccountCurrencyCode'
        }

        /// <summary>
        /// Test the property 'AccountCurrencySymbol'
        /// </summary>
        [Fact]
        public void AccountCurrencySymbolTest()
        {
            // TODO unit test for the property 'AccountCurrencySymbol'
        }

        /// <summary>
        /// Test the property 'AccountCurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void AccountCurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'AccountCurrencyDecimalPlaces'
        }
    }
}
