/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Brotal.FireflyIII.Model;
using Brotal.FireflyIII.Client;
using System.Reflection;

namespace Brotal.FireflyIII.Test.Model
{
    /// <summary>
    ///  Class for testing PiggyBankProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiggyBankPropertiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiggyBankProperties
        //private PiggyBankProperties instance;

        public PiggyBankPropertiesTests()
        {
            // TODO uncomment below to create an instance of PiggyBankProperties
            //instance = new PiggyBankProperties();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiggyBankProperties
        /// </summary>
        [Fact]
        public void PiggyBankPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiggyBankProperties
            //Assert.IsType<PiggyBankProperties>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'TargetDate'
        /// </summary>
        [Fact]
        public void TargetDateTest()
        {
            // TODO unit test for the property 'TargetDate'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'ObjectGroupId'
        /// </summary>
        [Fact]
        public void ObjectGroupIdTest()
        {
            // TODO unit test for the property 'ObjectGroupId'
        }

        /// <summary>
        /// Test the property 'ObjectGroupOrder'
        /// </summary>
        [Fact]
        public void ObjectGroupOrderTest()
        {
            // TODO unit test for the property 'ObjectGroupOrder'
        }

        /// <summary>
        /// Test the property 'ObjectGroupTitle'
        /// </summary>
        [Fact]
        public void ObjectGroupTitleTest()
        {
            // TODO unit test for the property 'ObjectGroupTitle'
        }

        /// <summary>
        /// Test the property 'Accounts'
        /// </summary>
        [Fact]
        public void AccountsTest()
        {
            // TODO unit test for the property 'Accounts'
        }

        /// <summary>
        /// Test the property 'ObjectHasCurrencySetting'
        /// </summary>
        [Fact]
        public void ObjectHasCurrencySettingTest()
        {
            // TODO unit test for the property 'ObjectHasCurrencySetting'
        }

        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }

        /// <summary>
        /// Test the property 'CurrencyName'
        /// </summary>
        [Fact]
        public void CurrencyNameTest()
        {
            // TODO unit test for the property 'CurrencyName'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Fact]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }

        /// <summary>
        /// Test the property 'CurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void CurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'CurrencyDecimalPlaces'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyId'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyIdTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyId'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyName'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyNameTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyName'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyCode'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyCodeTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyCode'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencySymbol'
        /// </summary>
        [Fact]
        public void PrimaryCurrencySymbolTest()
        {
            // TODO unit test for the property 'PrimaryCurrencySymbol'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyDecimalPlaces'
        }

        /// <summary>
        /// Test the property 'TargetAmount'
        /// </summary>
        [Fact]
        public void TargetAmountTest()
        {
            // TODO unit test for the property 'TargetAmount'
        }

        /// <summary>
        /// Test the property 'PcTargetAmount'
        /// </summary>
        [Fact]
        public void PcTargetAmountTest()
        {
            // TODO unit test for the property 'PcTargetAmount'
        }

        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }

        /// <summary>
        /// Test the property 'PcCurrentAmount'
        /// </summary>
        [Fact]
        public void PcCurrentAmountTest()
        {
            // TODO unit test for the property 'PcCurrentAmount'
        }

        /// <summary>
        /// Test the property 'LeftToSave'
        /// </summary>
        [Fact]
        public void LeftToSaveTest()
        {
            // TODO unit test for the property 'LeftToSave'
        }

        /// <summary>
        /// Test the property 'PcLeftToSave'
        /// </summary>
        [Fact]
        public void PcLeftToSaveTest()
        {
            // TODO unit test for the property 'PcLeftToSave'
        }

        /// <summary>
        /// Test the property 'SavePerMonth'
        /// </summary>
        [Fact]
        public void SavePerMonthTest()
        {
            // TODO unit test for the property 'SavePerMonth'
        }

        /// <summary>
        /// Test the property 'PcSavePerMonth'
        /// </summary>
        [Fact]
        public void PcSavePerMonthTest()
        {
            // TODO unit test for the property 'PcSavePerMonth'
        }
    }
}
