/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Brotal.FireflyIII.Model;
using Brotal.FireflyIII.Client;
using System.Reflection;

namespace Brotal.FireflyIII.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionStore
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionStoreTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionStore
        //private TransactionStore instance;

        public TransactionStoreTests()
        {
            // TODO uncomment below to create an instance of TransactionStore
            //instance = new TransactionStore();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionStore
        /// </summary>
        [Fact]
        public void TransactionStoreInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionStore
            //Assert.IsType<TransactionStore>(instance);
        }

        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

        /// <summary>
        /// Test the property 'ErrorIfDuplicateHash'
        /// </summary>
        [Fact]
        public void ErrorIfDuplicateHashTest()
        {
            // TODO unit test for the property 'ErrorIfDuplicateHash'
        }

        /// <summary>
        /// Test the property 'ApplyRules'
        /// </summary>
        [Fact]
        public void ApplyRulesTest()
        {
            // TODO unit test for the property 'ApplyRules'
        }

        /// <summary>
        /// Test the property 'FireWebhooks'
        /// </summary>
        [Fact]
        public void FireWebhooksTest()
        {
            // TODO unit test for the property 'FireWebhooks'
        }

        /// <summary>
        /// Test the property 'GroupTitle'
        /// </summary>
        [Fact]
        public void GroupTitleTest()
        {
            // TODO unit test for the property 'GroupTitle'
        }
    }
}
