/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Brotal.FireflyIII.Model;
using Brotal.FireflyIII.Client;
using System.Reflection;

namespace Brotal.FireflyIII.Test.Model
{
    /// <summary>
    ///  Class for testing UserGroupReadAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserGroupReadAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserGroupReadAttributes
        //private UserGroupReadAttributes instance;

        public UserGroupReadAttributesTests()
        {
            // TODO uncomment below to create an instance of UserGroupReadAttributes
            //instance = new UserGroupReadAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserGroupReadAttributes
        /// </summary>
        [Fact]
        public void UserGroupReadAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserGroupReadAttributes
            //Assert.IsType<UserGroupReadAttributes>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'InUse'
        /// </summary>
        [Fact]
        public void InUseTest()
        {
            // TODO unit test for the property 'InUse'
        }

        /// <summary>
        /// Test the property 'CanSeeMembers'
        /// </summary>
        [Fact]
        public void CanSeeMembersTest()
        {
            // TODO unit test for the property 'CanSeeMembers'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyId'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyIdTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyId'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyCode'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyCodeTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyCode'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencySymbol'
        /// </summary>
        [Fact]
        public void PrimaryCurrencySymbolTest()
        {
            // TODO unit test for the property 'PrimaryCurrencySymbol'
        }

        /// <summary>
        /// Test the property 'PrimaryCurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void PrimaryCurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'PrimaryCurrencyDecimalPlaces'
        }

        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Fact]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
    }
}
