/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Brotal.FireflyIII.Api;
using Brotal.FireflyIII.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Brotal.FireflyIII.Test.Api
{
    /// <summary>
    ///  Class for testing BudgetsApi
    /// </summary>
    public sealed class BudgetsApiTests : ApiTestsBase
    {
        private readonly IBudgetsApi _instance;

        public BudgetsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IBudgetsApi>();
        }

        /// <summary>
        /// Test DeleteBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteBudgetAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            await _instance.DeleteBudgetAsync(id, xTraceId);
        }

        /// <summary>
        /// Test DeleteBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteBudgetLimitAsyncTest()
        {
            string id = default!;
            string limitId = default!;
            Client.Option<Guid> xTraceId = default!;
            await _instance.DeleteBudgetLimitAsync(id, limitId, xTraceId);
        }

        /// <summary>
        /// Test GetBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetBudgetAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<DateOnly> start = default!;
            Client.Option<DateOnly> end = default!;
            var response = await _instance.GetBudgetAsync(id, xTraceId, start, end);
            var model = response.Ok();
            Assert.IsType<BudgetSingle>(model);
        }

        /// <summary>
        /// Test GetBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetBudgetLimitAsyncTest()
        {
            string id = default!;
            int limitId = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.GetBudgetLimitAsync(id, limitId, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetLimitSingle>(model);
        }

        /// <summary>
        /// Test ListAttachmentByBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListAttachmentByBudgetAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ListAttachmentByBudgetAsync(id, xTraceId, limit, page);
            var model = response.Ok();
            Assert.IsType<AttachmentArray>(model);
        }

        /// <summary>
        /// Test ListBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListBudgetAsyncTest()
        {
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            Client.Option<DateOnly> start = default!;
            Client.Option<DateOnly> end = default!;
            var response = await _instance.ListBudgetAsync(xTraceId, limit, page, start, end);
            var model = response.Ok();
            Assert.IsType<BudgetArray>(model);
        }

        /// <summary>
        /// Test ListBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListBudgetLimitAsyncTest()
        {
            DateOnly start = default!;
            DateOnly end = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.ListBudgetLimitAsync(start, end, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetLimitArray>(model);
        }

        /// <summary>
        /// Test ListBudgetLimitByBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListBudgetLimitByBudgetAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<DateOnly> start = default!;
            Client.Option<DateOnly> end = default!;
            var response = await _instance.ListBudgetLimitByBudgetAsync(id, xTraceId, start, end);
            var model = response.Ok();
            Assert.IsType<BudgetLimitArray>(model);
        }

        /// <summary>
        /// Test ListTransactionByBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListTransactionByBudgetAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            Client.Option<DateOnly> start = default!;
            Client.Option<DateOnly> end = default!;
            Client.Option<TransactionTypeFilter> type = default!;
            var response = await _instance.ListTransactionByBudgetAsync(id, xTraceId, limit, page, start, end, type);
            var model = response.Ok();
            Assert.IsType<TransactionArray>(model);
        }

        /// <summary>
        /// Test ListTransactionByBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListTransactionByBudgetLimitAsyncTest()
        {
            string id = default!;
            string limitId = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            Client.Option<TransactionTypeFilter> type = default!;
            var response = await _instance.ListTransactionByBudgetLimitAsync(id, limitId, xTraceId, limit, page, type);
            var model = response.Ok();
            Assert.IsType<TransactionArray>(model);
        }

        /// <summary>
        /// Test ListTransactionWithoutBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListTransactionWithoutBudgetAsyncTest()
        {
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            Client.Option<DateOnly> start = default!;
            Client.Option<DateOnly> end = default!;
            var response = await _instance.ListTransactionWithoutBudgetAsync(xTraceId, limit, page, start, end);
            var model = response.Ok();
            Assert.IsType<TransactionArray>(model);
        }

        /// <summary>
        /// Test StoreBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StoreBudgetAsyncTest()
        {
            BudgetStore budgetStore = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.StoreBudgetAsync(budgetStore, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetSingle>(model);
        }

        /// <summary>
        /// Test StoreBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StoreBudgetLimitAsyncTest()
        {
            string id = default!;
            BudgetLimitStore budgetLimitStore = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.StoreBudgetLimitAsync(id, budgetLimitStore, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetLimitSingle>(model);
        }

        /// <summary>
        /// Test UpdateBudget
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateBudgetAsyncTest()
        {
            string id = default!;
            BudgetUpdate budgetUpdate = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.UpdateBudgetAsync(id, budgetUpdate, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetSingle>(model);
        }

        /// <summary>
        /// Test UpdateBudgetLimit
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateBudgetLimitAsyncTest()
        {
            string id = default!;
            string limitId = default!;
            BudgetLimitUpdate budgetLimitUpdate = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.UpdateBudgetLimitAsync(id, limitId, budgetLimitUpdate, xTraceId);
            var model = response.Ok();
            Assert.IsType<BudgetLimitSingle>(model);
        }
    }
}
