/*
 * Firefly III API v6.3.0
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-08-16 @ 20:21:49 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.3.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Brotal.FireflyIII.Api;
using Brotal.FireflyIII.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Brotal.FireflyIII.Test.Api
{
    /// <summary>
    ///  Class for testing CurrencyExchangeRatesApi
    /// </summary>
    public sealed class CurrencyExchangeRatesApiTests : ApiTestsBase
    {
        private readonly ICurrencyExchangeRatesApi _instance;

        public CurrencyExchangeRatesApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ICurrencyExchangeRatesApi>();
        }

        /// <summary>
        /// Test DeleteSpecificCurrencyExchangeRate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSpecificCurrencyExchangeRateAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            await _instance.DeleteSpecificCurrencyExchangeRateAsync(id, xTraceId);
        }

        /// <summary>
        /// Test DeleteSpecificCurrencyExchangeRateOnDate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSpecificCurrencyExchangeRateOnDateAsyncTest()
        {
            string from = default!;
            string to = default!;
            string date = default!;
            Client.Option<Guid> xTraceId = default!;
            await _instance.DeleteSpecificCurrencyExchangeRateOnDateAsync(from, to, date, xTraceId);
        }

        /// <summary>
        /// Test DeleteSpecificCurrencyExchangeRates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteSpecificCurrencyExchangeRatesAsyncTest()
        {
            string from = default!;
            string to = default!;
            Client.Option<Guid> xTraceId = default!;
            await _instance.DeleteSpecificCurrencyExchangeRatesAsync(from, to, xTraceId);
        }

        /// <summary>
        /// Test ListCurrencyExchangeRates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListCurrencyExchangeRatesAsyncTest()
        {
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ListCurrencyExchangeRatesAsync(xTraceId, limit, page);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateArray>(model);
        }

        /// <summary>
        /// Test ListSpecificCurrencyExchangeRate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListSpecificCurrencyExchangeRateAsyncTest()
        {
            string id = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ListSpecificCurrencyExchangeRateAsync(id, xTraceId, limit, page);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateSingle>(model);
        }

        /// <summary>
        /// Test ListSpecificCurrencyExchangeRateOnDate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListSpecificCurrencyExchangeRateOnDateAsyncTest()
        {
            string from = default!;
            string to = default!;
            string date = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ListSpecificCurrencyExchangeRateOnDateAsync(from, to, date, xTraceId, limit, page);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateArray>(model);
        }

        /// <summary>
        /// Test ListSpecificCurrencyExchangeRates
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListSpecificCurrencyExchangeRatesAsyncTest()
        {
            string from = default!;
            string to = default!;
            Client.Option<Guid> xTraceId = default!;
            Client.Option<int> limit = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ListSpecificCurrencyExchangeRatesAsync(from, to, xTraceId, limit, page);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateArray>(model);
        }

        /// <summary>
        /// Test StoreCurrencyExchangeRate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StoreCurrencyExchangeRateAsyncTest()
        {
            CurrencyExchangeRateStore currencyExchangeRateStore = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.StoreCurrencyExchangeRateAsync(currencyExchangeRateStore, xTraceId);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateSingle>(model);
        }

        /// <summary>
        /// Test StoreCurrencyExchangeRatesByDate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StoreCurrencyExchangeRatesByDateAsyncTest()
        {
            string date = default!;
            CurrencyExchangeRateStoreByDate currencyExchangeRateStoreByDate = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.StoreCurrencyExchangeRatesByDateAsync(date, currencyExchangeRateStoreByDate, xTraceId);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateArray>(model);
        }

        /// <summary>
        /// Test StoreCurrencyExchangeRatesByPair
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StoreCurrencyExchangeRatesByPairAsyncTest()
        {
            string from = default!;
            string to = default!;
            Dictionary<string, string> requestBody = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.StoreCurrencyExchangeRatesByPairAsync(from, to, requestBody, xTraceId);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateArray>(model);
        }

        /// <summary>
        /// Test UpdateCurrencyExchangeRate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateCurrencyExchangeRateAsyncTest()
        {
            string id = default!;
            CurrencyExchangeRateUpdate currencyExchangeRateUpdate = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.UpdateCurrencyExchangeRateAsync(id, currencyExchangeRateUpdate, xTraceId);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateSingle>(model);
        }

        /// <summary>
        /// Test UpdateCurrencyExchangeRateByDate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateCurrencyExchangeRateByDateAsyncTest()
        {
            string from = default!;
            string to = default!;
            string date = default!;
            CurrencyExchangeRateUpdateNoDate currencyExchangeRateUpdateNoDate = default!;
            Client.Option<Guid> xTraceId = default!;
            var response = await _instance.UpdateCurrencyExchangeRateByDateAsync(from, to, date, currencyExchangeRateUpdateNoDate, xTraceId);
            var model = response.Ok();
            Assert.IsType<CurrencyExchangeRateSingle>(model);
        }
    }
}
