name: Build & Push Docker image to GHCR

on:
  push:
    branches: [ "main", "docker-support" ]
  release:
    types: [published]   # when you publish a GitHub Release

# Needed so the GITHUB_TOKEN can push to GHCR
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # owner/repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Don't try to push images from PRs coming from forks
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: speed up builds and enable multi-arch cross-compilation
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Auto-generate tags & labels:
      # - :latest on default branch
      # - :sha-<short> on every commit
      # - :<git tag> on releases (e.g., v1.2.3)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=tag

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64   # drop arm64 if you don’t need it
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
